name: Calling a reusable workflow 

on:
  workflow_dispatch:

jobs:
  job1:
    uses: RepositoriesForPoc/Resuable-Workflow-Called/.github/workflows/reusable-workflow.yml@main
    secrets:
      token: ${{ secrets.ENVPAT }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "demo"
